services:
  - type: web
    name: dulcelavanda
    runtime: python
    buildCommand: ""
    startCommand: gunicorn sistema.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sistema.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: dulcelavanda-db
          property: connectionString

databases:
  - name: dulcelavanda-db
    databaseName: dulcelavanda
    user: dulcelavanda_user
