# Generated by Django 5.0.6 on 2024-06-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(blank=True, default='/', max_length=5)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Covertores', 'Covertores - Cubrecamas'), ('Acolchado', 'Acolchado'), ('Bebe', 'Linea Bebé'), ('Hogar', 'Cocina'), ('Alimentación', 'Sábanas'), ('Juguetes', 'Accesorios'), ('Toallas', 'Toallas y Toallones'), ('Bano', 'Baño'), ('Almohadas', 'Almohadas'), ('Cortinas', 'Cortinas'), ('Frazadas', 'Frazadas')], max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('material', models.TextField(blank=True)),
                ('medida', models.TextField(blank=True)),
                ('tiene_stock', models.CharField(choices=[('Disponible', 'Disponible'), ('Sin stock', 'Sin stock')], max_length=20)),
                ('precio_lista', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('es_oferta', models.BooleanField(default=False)),
            ],
        ),
    ]
