# Generated by Django 5.1.5 on 2025-04-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Covertores', 'Covertores - Cubrecamas'), ('Acolchado', 'Acolchado'), ('Bebe', 'Linea Bebé'), ('Hogar', 'Cocina'), ('Sábanas', 'Sábanas'), ('Accesorios', 'Accesorios'), ('Toallas y Toallones', 'Toallas y Toallones'), ('Bano', 'Baño'), ('Almohadas', 'Almohadas'), ('Cortinas', 'Cortinas'), ('Frazadas', 'Frazadas')], max_length=50),
        ),
    ]
